### PR TITLE
:seedling: Stop reconciling HBMH on `unauthorized` error

### LINKED ISSUE #1895: Stop reconciling HetznerBaremetalHost on `unauthorized` error
Currently while provisioning a HetznerBaremetalHost, if wrong robot credentials are configured by the user then the HBMH's provisioning gets stuck without the reason being surfaced to the user through conditions. 

**Solution**:
When we recieve the error `unauthorized` on making the first call to Robot API in an HBMH's phase - we should set a condition indicating that the provided robot credentials are invalid and should stop reconciling it further.

---

Changes should be made on top of release branch `v1.1.x`

### PR DESCRIPTION
**Pull request by Dhairya-Arora01**
**What this PR does / why we need it**:
If we recieve the error `unauthorized` on making the first call to Robot API in an HBMH's phase then we should mark condition `CredentialsAvailable` to false with reason `RobotCredentialsInvalid` and stop reconciling.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1895

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

File: pkg/services/baremetal/host/host.go [hunk 1]
```diff
@@ -331,12 +350,31 @@ func (s *Service) ensureSSHKey(sshSecretRef infrav1.SSHSecretRef, sshSecret *cor
 	}
 	hetznerSSHKeys, err := s.scope.RobotClient.ListSSHKeys()
 	if err != nil {
+		// If Robot API returned "unauthorized" error - mark condition CredentialsAvailable as false
```
Comment (janiskemper) [inline pkg/services/baremetal/host/host.go]: do we need it here as well? And below? Or just in the first occasion where we call the API?

Comment (janiskemper) [inline pkg/services/baremetal/host/host.go]: my proposal would be that we add it once at the beginning and one while deprovisioning and otherwise remove it. I had a very hard time checking which pattern you used, e.g. if you always added it on every API call. I think that's not necessary. The code would look cleaner if we add it only on these two places. WDYT?

Comment (Dhairya-Arora01) [reply pkg/services/baremetal/host/host.go]: @janiskemper , the pattern that I followed is - check at the first API call of every provisioning state if we get an unauthorized error. 
Because what if the robot credentials are changed in between the provisioning states ? We have the hbmh reconciliation logic as state machine where we first try to deduce the provisioning state and then execute the logic of that provisioning state. That is why I think we need to check for unauthorized error on first API call in every provisioning state.

Comment (janiskemper) [reply pkg/services/baremetal/host/host.go]: problem I see is that it is also in utility functions right? I assumed that you did that, but I would still say that it is very hard to understand and especially to maintain. I think that the chance that the credentials are changed during provisioning is small enough so that it shouldn't matter.

Of course, it would be better to have it in every step. So do you have some idea how to make that transparent?

Comment (Dhairya-Arora01) [reply pkg/services/baremetal/host/host.go]: Hmm.... if the chances are very less that the credentials will change between provisioning states then


Lets just add it to these handlers

- [`actionPreparing`](https://github.com/syself/cluster-api-provider-hetzner/blob/b2d9c777a3711c6b2672654b25659d5d2f2cde1e/pkg/services/baremetal/host/host.go#L181) : Which is invoked as the first step of provisioning i.e. before registering. 
- [`actionDeprovisioning`](https://github.com/syself/cluster-api-provider-hetzner/blob/b2d9c777a3711c6b2672654b25659d5d2f2cde1e/pkg/services/baremetal/host/host.go#L2355) : Which is invoked on deprovisioning of the server.

Comment (janiskemper) [reply pkg/services/baremetal/host/host.go]: okay

**Review by janiskemper — COMMENTED** [review]
are you sure that we should re-use the existing condition? It seems risky to me honestly.. With some edge cases based on existing usage and future usage.. Maybe we should have a separate conditon.. 

I do agree that the name "CredentialsAvailable" is too generic for current usage, but we can change that in v1beta2. WDYT?

**Comment by Dhairya-Arora01** [comment]
@janiskemper the only other place where we set the `RobotCredentialsInvalid` condition is - when in the secret referenced in `HetznerCluster.Spec.HetznerSecret.Name` the specified robot credentials `username` and `password` are empty/not set.

This is the same as for HCloudTokenInvalid for hcloud machine.

We made the same changes there. Therefore I don't see a risk.

File: controllers/hetznerbaremetalhost_controller_test.go [hunk 2]
```diff
@@ -835,6 +835,93 @@ var _ = Describe("HetznerBareMetalHostReconciler - missing secrets", func() {
...
+				Data: map[string][]byte{
+					"private-key": []byte("os-ssh-secret-private-key"),
+					"sshkey-name": []byte("ssh-key-name"),
+					"public-key":  []byte("my-public-key"),
+				},
+			}
+			Expect(testEnv.Create(ctx, osSSHSecret)).To(Succeed())
+		})
+
+		It("should set CredentialsAvailable condition to false if Robot API returned unauthorized", func() {
```
Comment (janiskemper) [inline controllers/hetznerbaremetalhost_controller_test.go]: is this test not gonna panic? Because we first apply the objects and then add the mock later?

File: pkg/services/baremetal/host/host.go [hunk 3]
```diff
@@ -183,6 +183,23 @@ func (s *Service) actionPreparing(ctx context.Context) actionResult {
 
 	server, err := s.scope.RobotClient.GetBMServer(s.scope.HetznerBareMetalHost.Spec.ServerID)
 	if err != nil {
+		// If Robot API returned "unauthorized" error - mark condition CredentialsAvailable as false
```
Comment (janiskemper) [inline pkg/services/baremetal/host/host.go]: let's add this also to actionProvisioned

**Review by janiskemper — APPROVED** [review]
