### PR TITLE
:seedling: Skip machines with one WWN, if RAID is desired.

### LINKED ISSUE #1122: Controller should not pick hbmh with one disk, if swraid=true
/kind bug

if the hetzner-bare-metal-machine-template has swraid=true, then the controller should not pick a hbmh which has only one disk.

Up to now the controller picks the hbmh and after several minutes the process fails because installimage fails. 

You can see the error message of installimage in the Kubernetes event, but it is not immediately visible.

**What did you expect to happen:**

I expect the controller to ignore machines which have only one WWN in the hbmh, if the hetzner-bare-metal-machine-template has swraid=true.

**Anything else you would like to add:**

We should do the opposite check, too:

If the  hetzner-bare-metal-machine-template has swraid=false, then the controller should not pick a hbmh which has two WWNs.

[hbmh docs](https://github.com/syself/cluster-api-provider-hetzner/blob/ad6342c684236dda19d85fd12a06066dbb46ed76/docs/reference/hetzner-bare-metal-host.md?plain=1#L33) 

[hbmmt docs](https://github.com/syself/cluster-api-provider-hetzner/blob/ad6342c684236dda19d85fd12a06066dbb46ed76/docs/reference/hetzner-bare-metal-machine-template.md?plain=1#L47)

Implementation: 

There are two lists of WWNs: rootDeviceHints.raid.wwn and rootDeviceHints.wwn.

The controller should only take a machine wher swraid (from the hbmmt) matches the WWN of hbmh.

### PR DESCRIPTION
**Pull request by guettli**
**What this PR does / why we need it**:

Skip machines with one WWN, if RAID is desired.

Fixes #1122 

**Special notes for your reviewer**:

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — COMMENTED** [review]
Is this something that happens often? 
This should be documented accordingly. Right now people probably try to do this and wonder why the host does not get chosen. 

Should we also include a log or event for this?

**Comment by guettli** [comment]
> Is this something that happens often? This should be documented accordingly. Right now people probably try to do this and wonder why the host does not get chosen.
> 
> Should we also include a log or event for this?

in 88bd7188 i added a "reason", so that users understand why hosts were not picked.

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 1]
```diff
@@ -363,77 +366,121 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
 		}
+		if host.Spec.Status.ProvisioningState != infrav1.StateNone {
+			continue
+		}
+
+		// from now on each "continue" should add an entry
+		// to mapOfSkipReasons.
+		usableDevices++
+
+		if host.Spec.RootDeviceHints != nil &&
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:411]: this code block has to come last. If the host is in maintenance mode, then getting this reason is misleading

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 2]
```diff
@@ -363,77 +366,121 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
+					continue
+				}
+			}
+		}
 		if host.Spec.MaintenanceMode != nil && *host.Spec.MaintenanceMode {
+			mapOfSkipReasons["hbmh-in-maintenance-mode"]++
 			continue
 		}
 		if host.GetDeletionTimestamp() != nil {
+			mapOfSkipReasons["hbmh-has-deletion-timestamp"]++
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:439]: put this on top, this is a very strong reason (after "usableDevices")

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 3]
```diff
@@ -363,77 +366,121 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
 			continue
 		}
 		if host.Spec.Status.ErrorMessage != "" {
+			mapOfSkipReasons["hbmh-has-error-message-in-status"]++
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:443]: put this after deletion timestamp

**Review by janiskemper — CHANGES_REQUESTED** [review]

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 1 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal.go:428]: makes sense. Done in 40f22534

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 3 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal.go]: @janiskemper please take a look at the new code. Does it make sense now? I moved "label" up, because I think we should not look too deep in to machines which are not in our scope.

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 4]
```diff
@@ -363,71 +365,126 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
 	}
 
 	labelSelector := s.getLabelSelector()
 
-	availableHosts := make([]*infrav1.HetznerBareMetalHost, 0, len(hosts.Items))
+	usableHosts := make([]*infrav1.HetznerBareMetalHost, 0, len(hosts.Items))
 
+	mapOfSkipReasons := make(map[string]int)
+
+	availableDevices := 0
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:390]: hosts not devices, and don't mix available and usable.. You renamed something from "available" to "usable" but here you name your variable "available" again. We should stick to one!

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 5]
```diff
@@ -363,71 +365,126 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
 			continue
 		}
 
-		if !labelSelector.Matches(labels.Set(host.ObjectMeta.Labels)) {
-			continue
+		// This comes last, because now we would choose the machine, but we check
+		// if the config is correct.
+		if host.Spec.RootDeviceHints != nil &&
+			host.Spec.RootDeviceHints.IsValid() {
+			// If there are no RootDeviceHints, then the it should be ok that the hbmh gets picked.
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:434]: better text:
Even if there are no rootDeviceHints specified, the host is usable. After the phase registering, the process to provision the server stops and waits for the user to specify the rootDeviceHints. 
Here we want to check whether the specified rootDeviceHints fit with the InstallImage configuration of the HetznerBareMetalMachine. If not, it is not usable.

File: pkg/services/baremetal/baremetal/baremetal.go [hunk 6]
```diff
@@ -363,71 +365,126 @@ func (s *Service) getAssociatedHost(ctx context.Context) (*infrav1.HetznerBareMe
...
+					continue
+				}
+			}
 		}
 
-		if host.Spec.Status.ProvisioningState != infrav1.StateNone {
+		usableHosts = append(usableHosts, &hosts.Items[i])
+	}
+
+	reasons := make([]string, 0, len(mapOfSkipReasons))
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal.go:459]: can you put this in a utility function that outputs a string ("reasons")?

File: pkg/services/baremetal/baremetal/baremetal_test.go [hunk 7]
```diff
@@ -208,6 +234,9 @@ var _ = Describe("chooseHost", func() {
 		Hosts            []client.Object
 		HostSelector     infrav1.HostSelector
 		ExpectedHostName string
+		ExpectedReason   string
+		Swraid           int
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal_test.go:238]: can you define a separate struct for the test case below? There is no overlap in the properties you need  expect for "Hosts" and "ExpectedHostName". I think it is cleaner if we have two structs

File: pkg/services/baremetal/baremetal/baremetal_test.go [hunk 8]
```diff
@@ -276,6 +306,42 @@ var _ = Describe("chooseHost", func() {
 				ExpectedHostName: "hostWithLabel",
 			}),
 	)
+	DescribeTable("chooseHost(): Test empty result becaues RAID config does not match.",
```
Comment (janiskemper) [inline pkg/services/baremetal/baremetal/baremetal_test.go:309]:
```suggestion
	DescribeTable("chooseHost(): Test empty result because RAID config does not match.",
```

**Review by janiskemper — CHANGES_REQUESTED** [review]

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 4 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal.go:390]: We have three sets:

set 1: the big list which contains all devices.

set 2: Subset of set1. we removed the devices which are in use. This is called "available"

set 3: Subset of set2. We removed the one that don't match (like raid is wrong, labels don't match). This is called "usable".

I changed the name because I think it makes sense that there are more available devices than usable devices.

Does this make sense to you? Should I add a comment to the code?

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 5 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal.go]: yes, makes sense. Does the text of 1106b11b fit?

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 4 above)
Comment (janiskemper) [reply pkg/services/baremetal/baremetal/baremetal.go:390]: Ah I actually did not understand it. Maybe you can define "available" then before "usable" and quickly comment on it. 
However, it is still not "devices" but "hosts" ;)

File: pkg/services/baremetal/baremetal/baremetal.go (hunk 6 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal.go]: yes, makes sense. done in ab75bb93

File: pkg/services/baremetal/baremetal/baremetal_test.go (hunk 7 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal_test.go]: done in d286906e. I use unexported field names in the new struct, since there is no need to export them. ok?

File: pkg/services/baremetal/baremetal/baremetal_test.go (hunk 8 above)
Comment (guettli) [reply pkg/services/baremetal/baremetal/baremetal_test.go]: fixed.

**Comment by guettli** [comment]
@janiskemper please review

**Comment by janiskemper** [comment]
did you do more than fixing the test? If not, I'll approve

**Review by batistein — APPROVED** [review]

**Review by janiskemper — APPROVED** [review]
